services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2.7-alpine
  web:
    build:
      context: ./docker/
      args:
        - RUBY_VERSION=3.1.2
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - redis
      - db
    entrypoint: docker/entrypoint.sh
    ports:
      - "5000:5000"
    volumes:
      - .:/wired_chat:cached
    tty: true
    stdin_open: true

volumes:
  postgres:
