version: '3.7'

services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.0.9
  web:
    build:
        context: ./docker/
        args:
          - RUBY_VERSION=3.0.3
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    depends_on:
      - redis
      - postgres
    entrypoint: docker/entrypoint.sh
    ports:
      - "5000:5000"
    volumes:
      - .:/wired_chat:cached
    tty: true
    stdin_open: true

volumes:
    gems:
    postgres:
    rails_cache:
