default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: wired_chat_development

test:
  <<: *default
  database: wired_chat_test

production:
  <<: *default
  database: wired_chat_production
  username: wired_chat
  password: <%= ENV['WIRED_CHAT_DATABASE_PASSWORD'] %>
